### ISSUE TITLE
conda recipe discussion

### ISSUE THREAD

**Issue by stuarteberg** [JaneliaSciComp/SongExplorer#13]
These comments are written with the presumption that you'll be contributing your recipe to `conda-forge`.

---

## post-link.sh

Installing `pip` packages via a `post-link.sh` script is a bit strange.  I think most users would not expect that to happen.  I also doubt it would be approved in a `conda-forge` feedstock.

As a compromise, perhaps you could merely *recommend* to your user that they run `pip install` for the extra speedup?  [See here.][1]

[1]: https://stackoverflow.com/a/65334083/162094

---

### `source`

Just FYI, when it's time to submit a recipe to conda-forge, you'll need to replace `git_url` with a tarball `url`.

### `requirements:run:`

At least one of the packages listed in `meta.yaml` is not available on `conda-forge` as far as I can tell: `tensorflow-deps`.  Is it really necessary?  [This comment suggests that you don't need that dependency.][2]

[2]: https://github.com/conda-forge/tensorflow-feedstock/issues/259#issuecomment-1215757358

Same goes for `cuda-nvcc` and perhaps others.  Can they be omitted, and possibly recommended to the users as optional dependencies (either in the docs or in `post-link.sh` as described above)?

### `test`

You'll definitely need a `test` section before conda-forge will accept the recipe.

---

## build.sh

The install script for this package is rather non-standard.  That's owing to the fact that this project is not structured in the standard Python way.  From one perspective, that's irrelevant to conda-forge -- they are typically concerned with installing things according to the upstream package's expectations.  Still, in the interest of long-term maintainability, it might be worth making SongExplorer look more like most other Python tools.

**Comment by mkitti** [comment]
What a small world. In normal times, Stuart's office would be within line of sight of my cubicle, but alas we are not quite in normal times.

Coincidentally, @bjarthur, to whom Stuart's comment is directed, is the other Julia one user within our department. Ben has been using my Mac Studio to develop this conda recipe. I've been giving him some advice on developing this, but I decided to wait to push him towards conda-forge until he put together a "working" conda recipe. My gambit seems to have paid off since we've attracted the attention of Stuart, who is our resident conda-forge expert.

**Comment by bjarthur** [comment]
@ngam can you recommend someone to contact for help with getting a rust application into conda-forge?  i'm out of ideas for getting [this staged recipe](https://github.com/conda-forge/staged-recipes/pull/22454) to work on windows and not sure who to ping.  thanks!

**Comment by mkitti** [comment]
Have you tried the conda-forge gitter.im?

**Comment by bjarthur** [comment]
@ngam need your help again getting a [staged recipe](https://github.com/conda-forge/staged-recipes/pull/23298) reviewed.  could you ping someone for me again please?  it's been ready for three weeks. thanks.

**Comment by mkitti** [comment]
Try https://app.element.io/#/room/#conda-forge:matrix.org

**Comment by bjarthur** [comment]
hosting it here instead:  https://anaconda.org/janelia/songexplorer
